master-addr = "0.0.0.0:10343"
advertise-addr = "127.0.0.1:10343"
[etcd]
name = "server-master-3"
data-dir = "/tmp/df/master3"
peer-urls = "http://127.0.0.1:10003"
initial-cluster="server-master-1=http://127.0.0.1:10001,server-master-2=http://127.0.0.1:10002,server-master-3=http://127.0.0.1:10003"

